### ISSUE TITLE
Unable to deconvolve 512x512x512 image

### ISSUE THREAD

**Issue by RichardMyers** [StephanPreibisch/FourierConvolutionCUDALib#19]
moved from #18 

I tested your branch on a bead image in Fiji with regions from 32x32x32 up to 256x256 worked but 384x384 and 512x512 failed with memory error:

Exception in thread "Thread-30" java.lang.Error: Invalid memory access
    at com.sun.jna.Native.invokeVoid(Native Method)
    at com.sun.jna.Function.invoke(Function.java:374)
    at com.sun.jna.Function.invoke(Function.java:323)
    at com.sun.jna.Library$Handler.invoke(Library.java:236)
    at com.sun.proxy.$Proxy11.convolution3DfftCUDAInPlace(Unknown Source)
    at spim.process.fusion.deconvolution.MVDeconFFTThreads.convolve1BlockCUDA(MVDeconFFTThreads.java:65)
    at spim.process.fusion.deconvolution.MVDeconFFT.convolve1(MVDeconFFT.java:420)
    at spim.process.fusion.deconvolution.MVDeconvolution.runIteration(MVDeconvolution.java:362)
    at spim.process.fusion.deconvolution.MVDeconvolution.runIteration(MVDeconvolution.java:330)
    at spim.process.fusion.deconvolution.MVDeconvolution.<init>(MVDeconvolution.java:177)
    at spim.process.fusion.deconvolution.EfficientBayesianBased.fuseData(EfficientBayesianBased.java:259)
    at spim.fiji.plugin.Image_Fusion.fuse(Image_Fusion.java:173)
    at spim.fiji.plugin.Image_Fusion.fuse(Image_Fusion.java:88)
    at spim.fiji.spimdata.explorer.popup.FusionPopup$MyActionListener$1.run(FusionPopup.java:57)
    at java.lang.Thread.run(Thread.java:745)

I'm testing on a Quadro K2200 (mem=4096, cuda capability = 5.0)

I think this memory issue is a known constraint. If not, let me know and I can start a case for it.

**Comment by RichardMyers** [comment]
I ran this on a different system with larger specs.  This system is running with a Quadro M4000 (mem=8192MB and CUDA capability 5.2)

I was able to run a version of test_gpu_memory_reach here and this was the result:

Running 4 test cases...
C:/Users/Richard/Documents/GitHub/FourierConvolutionCUDALib/tests/test_gpu_memory_reach.cpp(194): fatal error in "identity_convolve_512": failed due to CUFFT_ALLOC_FAILED in C:/Users/Richard/Documents/GitHub/FourierConvolutionCUDALib/src/convolution3Dfft.cu at line 509

 do not use convolution3DfftCUDAInPlace on this GPU with shapes larger than (x,y,z) = 512x512x512

**Comment by RichardMyers** [comment]
@psteinb write in #18 

> that is semi-good news, I'd say. the 512**3 image would consume .5GB in RAM. for power-of-2 transforms, cufft typically consumes around 2.5x the memory of the input signal. it's quite strange that it would go up to 8x and run against the memory wall of your device. 
> are you using the K2200 for rendering the display as well? Another thing to try out would be to make the nvidia SDK examples ./3_Imaging/convolutionFFT2D or ./7_CUDALibraries/simpleCUFFT match 512**3 or 384**3 for single precision inputs. this way you could test your hypothesis stated above independent of fiji and friends.

**Comment by RichardMyers** [comment]
Also, this could be duplicate of #11 

I'll try out the SDK examples recommended by Peter.

**Comment by RichardMyers** [comment]
Also, to answer @psteinb 's question, my K2200 is used for rendering the display, so it could be using memory for that.  I should also try large data sets > 512 to see if it's related to #11.  But I did also fail at 384^3 so seems like a different issue.  Perhaps windows related even.

**Comment by psteinb** [comment]
any news on this? otherwise feel free to close it.

**Comment by RichardMyers** [comment]
No news; but I do think #11 is likely the same problem.  We can close this until we get some news from NVidia about why their own cufftEstimate3d fails at 512x512x512 .  Is there any sort of tracking for that case with NVidia?  I can pile on.
