### ISSUE TITLE
NaNs, memory issues

### ISSUE THREAD

**Issue by yaboyabo** [StephanPreibisch/FourierConvolutionCUDALib#22]
I am experiencing an error that might be related to several issues  posted here already. 
The problem is comparable to that of #9 (return of NaN after deconvolution) with all sizes above those that can be used for ArrayImg.
Ubuntu 14.04/16.04, OpenJDK8, Cuda 8
You can recreate the error by using large images with these options
ImgLib2 Container: CellImg
ImgLib2 container FFTs:ArrayImg
It will accept it but returns NaN.

However, when using a bounding box to make it fit as an ArrayImg it works.

I think it may come from the Java side. Using:
ImgLib2 Container: CellImg
ImgLib2 container FFTs:CellImg

    java.lang.ClassCastException: net.imglib2.img.cell.CellImg cannot be cast to net.imglib2.img.array.ArrayImg
    at spim.process.fusion.deconvolution.MVDeconFFTThreads.convolve1BlockCUDA(MVDeconFFTThreads.java:62)
    at spim.process.fusion.deconvolution.MVDeconFFT.convolve1(MVDeconFFT.java:420)
    at spim.process.fusion.deconvolution.MVDeconvolution.runIteration(MVDeconvolution.java:362)
    at spim.process.fusion.deconvolution.MVDeconvolution.runIteration(MVDeconvolution.java:330)
    at spim.process.fusion.deconvolution.MVDeconvolution.(MVDeconvolution.java:177)
    at spim.process.fusion.deconvolution.EfficientBayesianBased.fuseData(EfficientBayesianBased.java:259)
    at spim.fiji.plugin.Image_Fusion.fuse(Image_Fusion.java:173)
    at spim.fiji.plugin.Image_Fusion.run(Image_Fusion.java:76)
    at ij.IJ.runUserPlugIn(IJ.java:217)
    at ij.IJ.runPlugIn(IJ.java:181)
    at ij.Executer.runCommand(Executer.java:137)
    at ij.Executer.run(Executer.java:66)
    at java.lang.Thread.run(Thread.java:745)

ImgLib2 Container: PlanarImg
ImgLib2 container FFTs:PlanarImg

    java.lang.ClassCastException: net.imglib2.img.imageplus.FloatImagePlus cannot be cast to net.imglib2.img.array.ArrayImg
    at spim.process.fusion.deconvolution.MVDeconFFTThreads.convolve1BlockCUDA(MVDeconFFTThreads.java:62)
    at spim.process.fusion.deconvolution.MVDeconFFT.convolve1(MVDeconFFT.java:420)
    at spim.process.fusion.deconvolution.MVDeconvolution.runIteration(MVDeconvolution.java:362)
    at spim.process.fusion.deconvolution.MVDeconvolution.runIteration(MVDeconvolution.java:330)
    at spim.process.fusion.deconvolution.MVDeconvolution.(MVDeconvolution.java:177)
    at spim.process.fusion.deconvolution.EfficientBayesianBased.fuseData(EfficientBayesianBased.java:259)
    at spim.fiji.plugin.Image_Fusion.fuse(Image_Fusion.java:173)
    at spim.fiji.plugin.Image_Fusion.run(Image_Fusion.java:76)
    at ij.IJ.runUserPlugIn(IJ.java:217)
    at ij.IJ.runPlugIn(IJ.java:181)
    at ij.Executer.runCommand(Executer.java:137)
    at ij.Executer.run(Executer.java:66)
    at java.lang.Thread.run(Thread.java:745)

Edit: the NaN problem when using ImgLib2 container FFTs:ArrayImg seems to only appear when using precomputed weights.
Seems to work with block sizes 128/256/512 and virtual weights.
Maybe @tibuch can let us know if that was the option he used. 

cheers

**Comment by StephanPreibisch** [comment]
Hi, I am sorry, I do not have the hardware right now to test it. I wrote the CUDA calls specifically only for ArrayImg, so I am not sure anything else works with CUDA. I am in the process of re-writing everything and will try to solve these problems in the process. I will keep you updated.

**Comment by StephanPreibisch** [comment]
In a new release on master it blocks executing not supported combinations of ImgFactories + CUDA ...

**Comment by yaboyabo** [comment]
Thanks a lot for your response. No worries it works fine given the constraints. Part of the motivation, besides letting you know, was informing other users to save them some time. 
Looking forward to the rewritten version!

**Comment by psteinb** [comment]
Can this be closed?

**Comment by tibuch** [comment]
I don't have the hardware anymore. But I believe the blocking-fix will resolve it. From my side it can be closed, as well as the referenced one.
Thank you all!

**Comment by yaboyabo** [comment]
Yes from my side it can be closed too.
Thanks all.
