### ISSUE TITLE
Error looking up function 'convolve_15'

### ISSUE THREAD

**Issue by mcahn** [StephanPreibisch/FourierConvolutionCUDALib#23]
I'm attempting to build and run the CUDA code for Multiview Reconstruction.

When I select Multiview Reconstruction > Batch processing > Detect Interest Points for Registration

and run it on one of the Nvidia K20's in the system, I eventually get this error:

java.lang.UnsatisfiedLinkError: Error looking up function 'convolve_15': /tigress/MOLBIO/local/src/Fiji.app/java/linux-amd64/jdk1.8.0_66/jre/lib/amd64/libFourierConvolutionCUDALib.so: undefined symbol: convolve_15

The .so library is from https://github.com/StephanPreibisch/FourierConvolutionCUDALib, which I've built with gcc 5.3.1 and cudatoolkit 8.0.  Fiji is running under Redhat Enterprise Linux 6.9.  If someone could help me understand where convolve_15 comes from it would be much appreciated.

-- Matthew

**Comment by psteinb** [comment]
`convolve_15` is not defined in this project. Can you post the full error log to see where the problem was caused in the java stack?

**Comment by mcahn** [comment]
Here is the contents of the Fiji log Window and the Exception window.

Fiji Log window...

Using spimdata version: 0.9-revision
Using spimreconstruction version: 5.0.16
angles selected: 0, 45, 90, 135, 180, 225, 270
channels selected: 0
illuminations selected: 0
tiles selected: 0
Timepoints selected: 0
Looking for native libraries ending with '.so', '.lib' in directory: '/tigress/MOLBIO/local/src/Fiji.app' ... 
Trying to load following library: /tigress/MOLBIO/local/src/Fiji.app/libFourierConvolutionCUDALib.so
Using an outdated version of the CUDA libs, cannot query free memory. Assuming total memory.
Using an outdated version of the CUDA libs, cannot query free memory. Assuming total memory.
Using device Tesla K20m (id=0, mem=4742MB (4742MB free), CUDA capability 3.5)
(Mon Aug 07 11:46:47 EDT 2017): Requesting Img from ImgLoader (tp=0, setup=0)
(Mon Aug 07 11:46:47 EDT 2017): Downsampling in XY 2x ...
Mon Aug 07 11:46:48 EDT 2017: Opening '/tigress/tstern/HisYFP-SPIM (2)/././spim_TL18_Angle0.tif' [1388x1040x81 ch=0 tp=0 type=uint8 image=ArrayImg<FloatType>]
(Mon Aug 07 11:46:51 EDT 2017): min intensity = 0.0, max intensity = 251.9375
(Mon Aug 07 11:46:51 EDT 2017): computing difference-of-gausian (sigma=1.8, threshold=0.008, sigma1=(1.7291616201400757, 1.7291616201400757, 1.7291616201400757), sigma2=(2.0813581943511963, 2.0813581943511963, 2.0813581943511963))
Mon Aug 07 11:46:51 EDT 2017: Computing DoG image (GPU).
CUDA-Device 0, mem=3556MB (1%), required mem=223MB, need to split up into 1 blocks: 1x1x1
Conovlving image as one single block.
Copying data took 424ms



Fiji Exception Window...


(Fiji Is Just) ImageJ 2.0.0-rc-61/1.51n; Java 1.8.0_66 [64-bit]; Linux 2.6.32-696.6.3.el6.x86_64; 896MB of 266769MB (<1%)
 
java.lang.UnsatisfiedLinkError: Error looking up function 'convolve_15': /tigress/MOLBIO/local/src/Fiji.app/libFourierConvolutionCUDALib.so: undefined symbol: convolve_15
	at com.sun.jna.Function.<init>(Function.java:245)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:566)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:542)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:528)
	at com.sun.jna.Library$Handler.invoke(Library.java:228)
	at com.sun.proxy.$Proxy11.convolve_15(Unknown Source)
	at spim.process.cuda.CUDASeparableConvolutionFunctions.gauss(CUDASeparableConvolutionFunctions.java:203)
	at spim.process.cuda.CUDASeparableConvolutionFunctions.gauss(CUDASeparableConvolutionFunctions.java:108)
	at spim.process.interestpointdetection.DifferenceOfGaussianCUDA$CUDAOutput.process(DifferenceOfGaussianCUDA.java:165)
	at spim.process.interestpointdetection.DifferenceOfGaussianNewPeakFinder$1.run(DifferenceOfGaussianNewPeakFinder.java:99)
	at java.lang.Thread.run(Thread.java:745)
	at mpicbg.imglib.multithreading.SimpleMultiThreading.startAndJoin(SimpleMultiThreading.java:139)
	at spim.process.interestpointdetection.DifferenceOfGaussianNewPeakFinder.process(DifferenceOfGaussianNewPeakFinder.java:111)
	at spim.process.interestpointdetection.ProcessDOG.compute(ProcessDOG.java:153)
	at spim.fiji.plugin.interestpointdetection.DifferenceOfGaussian.findInterestPoints(DifferenceOfGaussian.java:132)
	at spim.fiji.plugin.Interest_Point_Detection.detectInterestPoints(Interest_Point_Detection.java:191)
	at spim.fiji.plugin.Interest_Point_Detection.run(Interest_Point_Detection.java:89)
	at ij.IJ.runUserPlugIn(IJ.java:217)
	at ij.IJ.runPlugIn(IJ.java:181)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mcahn** [comment]
The convolve_15 function seems to be **referenced** in the code in this project:

    https://github.com/fiji/SPIM_Registration

in this file:

    src/main/java/spim/process/cuda/CUDASeparableConvolution.java

        cuda.convolve_15( ...


And the convolve_15 function seems to be **defined** in the code in this project:

    https://github.com/StephanPreibisch/SeparableConvolutionCUDALib

in this file:

    src/separableConvolution_15.cu

        extern "C" int convolve_15(...

Do I need to build SeparableConvolutionCUDALib? I built FourierConvolutionCUDALib.

**Comment by StephanPreibisch** [comment]
Hi, yes, exactly, there are two different CUDA libraries, one for FFT-based convolution, one for separable convolution, which will result in two different library files (dll's, .so, etc.). Both libraries are linked from the main page: http://imagej.net/Multiview-Reconstruction

Hope this helps,
Stephan
